export const LEVEL_TITLES = [
  // Levels 1-5: Beginner's Journey
  "Habit Novice",
  "Routine Starter",
  "Discipline Seeker",
  "Pattern Builder",
  "Consistency Keeper",
  
  // Levels 6-10: Intermediate Growth
  "Habit Explorer",
  "Progress Tracker",
  "Dedication Finder",
  "Rhythm Master",
  "Foundation Champion",
  
  // Levels 11-20: Skilled Practitioner
  "Discipline Sculptor",
  "Rhythm Builder",
  "Milestone Maker",
  "Focus Engineer",
  "Goal Tracker",
  "Dedication Strategist",
  "Persistence Pilot",
  "Momentum Keeper",
  "Milestone Chaser",
  "Effort Sustainer",

  // Levels 21-50: Habit Mastery
  "Momentum Maverick",
  "Focus Virtuoso",
  "Dedication Conqueror",
  "Routine Alchemist",
  "Resilience Sculptor",
  "Master Planner",
  "Streak Weaver",
  "Goal Guardian",
  "Perseverance Artisan",
  "Milestone Visionary",
  "Rhythm Commander",
  "Habitologist",
  "Progress Tactician",
  "Consistency Commander",
  "Milestone Strategist",
  "Discipline Innovator",
  "Determination Pilot",
  "Pace Setter",
  "Goal Sculptor",
  "Effort Strategist",
  "Consistency Architect",
  "Resilience Vanguard",
  "Perseverance Guardian",
  "Dedication Tactician",
  "Momentum Strategist",
  "Progress Architect",
  "Growth Strategist",
  "Goal Visionary",
  "Rhythm Champion",
  "Streak Maestro",

  // Levels 51-99: Elite Performers
  "Habit Titan",
  "Momentum Virtuoso",
  "Consistency Luminary",
  "Dedication Conqueror",
  "Persistence Luminary",
  "Growth Sentinel",
  "Streak Innovator",
  "Rhythm Vanguard",
  "Goal Virtuoso",
  "Focus Luminary",
  "Progress Guardian",
  "Momentum Alchemist",
  "Consistency Innovator",
  "Perseverance Vanguard",
  "Dedication Visionary",
  "Persistence Champion",
  "Resilience Titan",
  "Habit Commander",
  "Goal Maverick",
  "Focus Sentinel",
  "Rhythm Pioneer",
  "Streak Guardian",
  "Effort Commander",
  "Dedication Strategist",
  "Perseverance Commander",
  "Consistency Visionary",
  "Growth Commander",
  "Momentum Titan",
  "Habit Visionary",
  "Persistence Architect",
  "Goal Pioneer",
  "Rhythm Tactician",
  "Dedication Luminary",
  "Momentum Champion",
  "Effort Innovator",
  "Growth Alchemist",
  "Focus Architect",
  "Rhythm Maverick",
  "Progress Titan",
  "Momentum Vanguard",
  "Streak Commander",
  "Consistency Titan",
  "Effort Sentinel",
  "Perseverance Tactician",
  "Rhythm Alchemist",
  "Momentum Visionary",
  "Focus Virtuoso",
  "Goal Sentinel",
  "Habit Luminary",
  "Legendary Streak Architect",

  // Level 100: Ultimate Habit Legend
  "Eternal Apex Streak Champion"
]